#ifndef VERSION_H
#define VERSION_H

#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 6
#define APP_VERSION_BUILD 5
#define APP_VERSION_PATCH 0
#define APP_VERSION_STR QString("%1.%2.%3").arg(APP_VERSION_MAJOR).arg(APP_VERSION_MINOR).arg(APP_VERSION_BUILD)

#endif // VERSION_H
